//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartAdminMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class colaborador_depto
    {
        public int id_col_depto { get; set; }
        public string colaborador_id { get; set; }
        public int depto_id { get; set; }
        public System.DateTime fec_ini_trabajo { get; set; }
        public System.DateTime fec_fin_trabajo { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Departamento Departamento { get; set; }
    }
}
