//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartAdminMvc.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SmartAdminMvcEntities1 : DbContext
    {
        public SmartAdminMvcEntities1()
            : base("name=SmartAdminMvcEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Calficacion> Calficacion { get; set; }
        public virtual DbSet<Categoria> Categoria { get; set; }
        public virtual DbSet<colaborador_depto> colaborador_depto { get; set; }
        public virtual DbSet<Departamento> Departamento { get; set; }
        public virtual DbSet<Recurso> Recurso { get; set; }
        public virtual DbSet<Ticket> Ticket { get; set; }
        public virtual DbSet<Urgencia> Urgencia { get; set; }
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<colaborador_depar> colaborador_depar { get; set; }
    
        public virtual int sp_ticket_usuario(Nullable<int> colaborador)
        {
            var colaboradorParameter = colaborador.HasValue ?
                new ObjectParameter("colaborador", colaborador) :
                new ObjectParameter("colaborador", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ticket_usuario", colaboradorParameter);
        }
    }
}
