//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartAdminMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int id_ticket { get; set; }
        public string id_colaborador { get; set; }
        public int id_recurso { get; set; }
        public int id_urgencia { get; set; }
        public string descp_falla { get; set; }
        public System.DateTime fech_emision { get; set; }
        public Nullable<System.DateTime> fech_asignacion { get; set; }
        public Nullable<System.DateTime> fech_fin { get; set; }
        public string estado_ticket { get; set; }
        public string encargado { get; set; }
        public string supervisor { get; set; }
        public string comentario { get; set; }
        public string obsevacion { get; set; }
        public Nullable<int> id_calificacion { get; set; }
        public byte[] imagen { get; set; }
        public string solucion { get; set; }
        public bool acti_encargado { get; set; }
        public bool acti_supervisor { get; set; }
        public bool aceptar { get; set; }
        public bool cerrado { get; set; }
        public bool verificar { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
        public virtual AspNetUsers AspNetUsers2 { get; set; }
        public virtual Calficacion Calficacion { get; set; }
        public virtual Recurso Recurso { get; set; }
        public virtual Urgencia Urgencia { get; set; }
    }
}
